version: "2"

services:

  interlock:
    image: ehazlett/interlock:master
    command: run -c /etc/interlock/config.toml
    ports:
      - 8080
    volumes:
      - ./config.toml:/etc/interlock/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    
  nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
      - 80:80
    labels:
      - "interlock.ext.name=nginx"
    links:
      - interlock:interlock
    depends_on:
      - interlock
      
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --smallfiles --storageEngine wiredTiger

